# GitHub Action for generating a contribution graph with a snake eating your contributions

name: Generate Snake

# 控制工作流的触发时机
on:
  schedule:
      # 每12小时运行一次
    - cron: "0 */12 * * *"
  # 允许您在 Actions 标签页手动触发此工作流
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # 生成贪吃蛇动画
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          # 您的 GitHub 用户名，下面的代码会自动获取
          github_user_name: ${{ github.repository_owner }}

          # 指定生成的动画文件路径
          # 格式: dist/github-snake.svg
          # 您也可以生成 gif: dist/github-snake.gif
          outputs: dist/github-snake.svg

      # 将生成的文件推送到一个专门的分支
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
